### ISSUE TITLE
Case Sensitivity

### ISSUE THREAD

**Issue by mrthepope** [Shawminator/DayZeEditor#13]
Hey - not sure if you will ever see this but - there is an issue with the eEditor and the Expansion Market. Long story short, as soon as you click the option to manage the "Expansion Market" the eEditor converts all of the Market related files to UPPERCASE. I'm not sure if something changed recently from the Expansion team BUT - The Expansion Market Mod seems to be looking for case sensitive files. If it cannot find them, it refreshes the folders with clean ones.

-- Example --

WEAPONS.json -- Invalid, results in new Weapons.json file being created

The server will now have two copies of the "same" file.

Took a few minutes to figure this out :-). Suggestion would be to ignore filename structure (leave as is).

Love this tool btw

MrThePope

**Comment by Shawminator** [comment]
can i ask are you using a hosting service or a dedicated box?

**Comment by mrthepope** [comment]
Nitrado

It’s a good question though. I have a local test box I can try. Didn’t
occur to me that Nitrado could be doing something weird.

**Comment by Shawminator** [comment]
ive found when using hosting the files are like case specific, 
for example you replace Weapons.json with WEAPONS.json it gets a bit bugged
for hosting when i was using hosting i had to completly empty the folder and then upload the files so that they were new and not replacing any
this was for the market, trader folders in profiles and the expansion folder in the missions for traders maps and trader zones

anyway im updating the market for the sub folders in market category files so imm removing the upper case forcing so hopefully wont be an issue after i update the tool

**Comment by mrthepope** [comment]
Appreciate the feedback and response. I’m going to check it out with my
test box. I wish there was somewhere to publish a support type article for
the expansion. I’ve seen quite a few people struggle with the Market not
respecting settings and I wonder if this is a similar problem.

Either way, thanks again and I really do love the tool!

**Comment by Shawminator** [comment]
Removed Case Forcing..
